"""init_tables

Revision ID: 73def6990d03
Revises: 
Create Date: 2021-01-18 14:26:34.862862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73def6990d03'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_user', sa.Integer(), nullable=False),
    sa.Column('car_name', sa.String(length=20), nullable=True),
    sa.Column('car_license_plate', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('openId', sa.String(length=128), nullable=True),
    sa.Column('userType', sa.SmallInteger(), nullable=True),
    sa.Column('avatarUrl', sa.String(length=200), nullable=True),
    sa.Column('modified', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('openId')
    )
    op.create_table('credit_card',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('credit_card_type', sa.SmallInteger(), nullable=True),
    sa.Column('credit_card_num', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_cars_relation',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('car_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['car.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('order',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('credit_card_id', sa.Integer(), nullable=True),
    sa.Column('order_comment', sa.String(length=300), nullable=True),
    sa.Column('order_price', sa.Integer(), nullable=True),
    sa.Column('order_counting_time', sa.DateTime(), nullable=True),
    sa.Column('order_status', sa.Enum('WAIT_PAYMENT', 'COMPLETE'), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['car.id'], ),
    sa.ForeignKeyConstraint(['credit_card_id'], ['credit_card.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_order_status'), 'order', ['order_status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_order_status'), table_name='order')
    op.drop_table('order')
    op.drop_table('user_cars_relation')
    op.drop_table('credit_card')
    op.drop_table('user')
    op.drop_table('car')
    # ### end Alembic commands ###
